version: '3.4'

x-backend:
  &backend
  build:
    context: ./backend
    dockerfile: Dockerfile.dev
  environment:
    RAILS_ENV: development
    DB_USERNAME: postgres
    DB_PASSWORD: secret
    DB_HOST: db
    DB_PORT: 5432
    DB_NAME: db
    SECRET_KEY_BASE: STUB
  stdin_open: true
  tty: true
  volumes:
    - ./backend:/backend:rw
    - /backend/vendor/bundle

services:
  backend:
    <<: *backend
    ports:
      - 3000:3000/tcp
    depends_on:
      - db

  db:
    image: postgres:11.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./client:/client
      - /client/node_modules

volumes:
  bundle_cache:
  postgres:
